CREATE DATABASE PRODUCT_SELLING;
USE PRODUCT_SELLING;
CREATE TABLE SALESMAN (SALESMAN_ID INTEGER, SALESMAN_NAME VARCHAR (20), CITY VARCHAR (20), COMMISSION VARCHAR (20), PRIMARY KEY (SALESMAN_ID));
SELECT * FROM SALESMAN;
CREATE TABLE CUSTOMER1 (CUSTOMER_ID INTEGER,CUST_NAME VARCHAR (20),CITY VARCHAR (20),GRADE INTEGER,PRIMARY KEY (CUSTOMER_ID),SALESMAN_ID INTEGER REFERENCES SALESMAN (SALESMAN_ID) ON DELETE SET NULL);
SELECT * FROM CUSTOMER1 ;
CREATE TABLE ORDERS (ORDER_NO INTEGER,PURCHASE_AMT INTEGER, ORD_DATE DATE,PRIMARY KEY (ORDER_NO),CUSTOMER_ID INTEGER REFERENCES CUSTOMER1 (CUSTOMER_ID) ON DELETE CASCADE, SALESMAN_ID INTEGER REFERENCES SALESMAN (SALESMAN_ID) ON DELETE CASCADE);
SELECT * FROM ORDERS;
INSERT INTO SALESMAN VALUES (1000, 'SHASHANK','BANGALORE','25 %'), (2000, 'VEDANTH','BANGALORE','20 %'), (3000, 'DEEPAK','MYSORE','15 %'),(4000, 'VIKAS','DELHI','30 %'),(5000, 'HARSHA','HYDRABAD','15 %');
